// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet.Context;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet.Entities.Commentaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCommentaire")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuteurId");

                    b.HasIndex("TicketId");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("Projet.Entities.Priorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomPriorite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Priorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomPriorite = "Basse"
                        },
                        new
                        {
                            Id = 2,
                            NomPriorite = "Moyenne"
                        },
                        new
                        {
                            Id = 3,
                            NomPriorite = "Haute"
                        },
                        new
                        {
                            Id = 4,
                            NomPriorite = "Critique"
                        });
                });

            modelBuilder.Entity("Projet.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomRole = "Administrateur"
                        },
                        new
                        {
                            Id = 2,
                            NomRole = "Technicien"
                        },
                        new
                        {
                            Id = 3,
                            NomRole = "Employe"
                        });
                });

            modelBuilder.Entity("Projet.Entities.Statut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomStatut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomStatut = "Nouveau"
                        },
                        new
                        {
                            Id = 2,
                            NomStatut = "En cours"
                        },
                        new
                        {
                            Id = 3,
                            NomStatut = "Résolu"
                        },
                        new
                        {
                            Id = 4,
                            NomStatut = "Clôturé"
                        });
                });

            modelBuilder.Entity("Projet.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreateurId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FichierUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrioriteId")
                        .HasColumnType("int");

                    b.Property<int>("StatutId")
                        .HasColumnType("int");

                    b.Property<int?>("TechnicienId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreateurId");

                    b.HasIndex("PrioriteId");

                    b.HasIndex("StatutId");

                    b.HasIndex("TechnicienId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Projet.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Projet.Entities.Commentaire", b =>
                {
                    b.HasOne("Projet.Entities.User", "Auteur")
                        .WithMany("Commentaires")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet.Entities.Ticket", "Ticket")
                        .WithMany("Commentaires")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Projet.Entities.Ticket", b =>
                {
                    b.HasOne("Projet.Entities.User", "Createur")
                        .WithMany("TicketsCrees")
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Projet.Entities.Priorite", "Priorite")
                        .WithMany("Tickets")
                        .HasForeignKey("PrioriteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet.Entities.Statut", "Statut")
                        .WithMany("Tickets")
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet.Entities.User", "Technicien")
                        .WithMany("TicketsAssignes")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Createur");

                    b.Navigation("Priorite");

                    b.Navigation("Statut");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("Projet.Entities.User", b =>
                {
                    b.HasOne("Projet.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Projet.Entities.Priorite", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Projet.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Projet.Entities.Statut", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Projet.Entities.Ticket", b =>
                {
                    b.Navigation("Commentaires");
                });

            modelBuilder.Entity("Projet.Entities.User", b =>
                {
                    b.Navigation("Commentaires");

                    b.Navigation("TicketsAssignes");

                    b.Navigation("TicketsCrees");
                });
#pragma warning restore 612, 618
        }
    }
}
